name: Build and deploy Angular app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'

      - name: Install and build
        working-directory: artisan
        run: |
          npm cache clean --force
          npm install -g @angular/cli
          npm install --no-optional
          npm run build -- --configuration production

      - name: Copy web.config
        run: |
          cp artisan/web.config artisan/dist/app/browser/

      - name: Create deployment package
        run: |
          cd artisan/dist/app/browser
          zip -r ../../../../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Prepare for deployment
        run: unzip release.zip -d ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4190740B6AF5451A92624C576DC58150 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5323485CE2724E43B2CF7BF9866CE852 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6E4B2A9F988455FAC5404FD8B54D3E0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'artisan-market'
          slot-name: 'Production'
          package: ./app
